import Head from "next/head";
import { Reorder } from "framer-motion";
import { useState } from "react";
import { motion } from "framer-motion";

import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import Button from "../components/Button/Button";
import Feature from "../components/Feature/Feature";

import styles from "../styles/Home.module.css";

const initialFeatures = ["Cloud File Types", "Select app from separate pages", "QA Platforms to check", "Another one", "A last one"]

export default function Home() {
  const [features, setFeatures] = useState(initialFeatures);
  const transition = { duration: 4, yoyo: Infinity, ease: "easeInOut" };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.app}>
        <div className={styles.hillChart}>
          <p className={styles.name}>Cloud Files</p>
          <svg width="720" height="162" viewBox="0 0 720 162" fill="none" xmlns="http://www.w3.org/2000/svg" className={styles.hill}>
            <motion.path d="M0 161C184 161 264 1 360 1C456 1 520 161 720 161" />
          </svg>
          <div className={styles.indicators}>
            <p>Figuring things out</p>
            <p>Making it happen</p>
          </div>
          {/* <motion.div 
            className={styles.dot}
            transition={transition}
            style={{ offsetPath: "path('M0 161C184 161 264 1 360 1C456 1 520 161 720 161')" }}
          ></motion.div> */}
        </div>
        <div className={styles.features}>
          <p>Features</p>
          <Reorder.Group axis="y" values={features} onReorder={setFeatures} className={styles.featuresList} as="div">
            {features.map((feature) => (
              <Feature key={feature} name={feature} />
            ))}
          </Reorder.Group>
          <Button label="Add a feature"/>
        </div>
        <div className={styles.actions}></div>
      </main>
      <Footer />
    </>
  )
}